export enum SERVICE_WORKER_MESSAGE_TYPE {
  SW_CONNECT_VERIFY_WITH_CONTENT_SCRIPT = "SW_CONNECT_VERIFY_WITH_CONTENT_SCRIPT",
}

export enum EXTENSION_COMMUTE_MESSAGE_TYPE {
  CONNECTION_REQUEST = "CONNECTION_REQUEST",
}

export enum POPUP_MESSAGE_TYPE {
  CHECK_IF_WIDGET_IS_INJECTED = "CHECK_IF_WIDGET_IS_INJECTED",
}
